# Generated by Django 3.2.4 on 2021-06-11 09:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_react_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
    ]
