# Generated by Django 3.2.4 on 2021-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pytorch_label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
